version: "3"
services:
  nginx: 
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 30080:80
    networks:
      - macnet
  api:
    image: maclookup_api
    expose:
      - "80"
    networks:
      - macnet
networks:
  macnet: